[package]
name = "pcap-deduper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = "0.16.0"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
